version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_assign.zip .
      - cd ..
      - zip -g deployment_package_assign.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_assign.zip s3://lambda-github-code/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name lambda_execution_from_github --s3-bucket lambda-github-code --s3-key deployment_package_assign.zip
      - echo "Deployment complete!"